'use client';
import {useEffect,useRef,useState,type PointerEvent as ReactPointerEvent} from 'react';
import {Volume2,VolumeX,Pause,Play,Settings2,Maximize,Compass,Map,Heart,Wind,Zap,Fish,ChevronRight,RotateCcw,MousePointer2,HelpCircle,Waves,Leaf,Sun,BookOpen,X,Check,Navigation,Save,Target,ChevronsUp,Anchor,Shield,Skull,Crosshair} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Engine,initial,type Snapshot} from '@/lib/game/engine';
import {LANDMARKS} from '@/lib/game/world';
import {normalizeJoystick} from '@/lib/game/input';
export default function Game(){
 const mount=useRef<HTMLDivElement>(null),map=useRef<HTMLCanvasElement>(null),engine=useRef<Engine|null>(null),joyPointer=useRef<number|null>(null),burstPointer=useRef<number|null>(null);
 const [s,setS]=useState<Snapshot>(initial),[ready,setReady]=useState(false),[error,setError]=useState(''),[paused,setPaused]=useState(false),[settings,setSettings]=useState(false),[help,setHelp]=useState(false),[journal,setJournal]=useState(false),[muted,setMuted]=useState(false),[quality,setQuality]=useState(2),[sens,setSens]=useState(1),[bigMap,setBigMap]=useState(false),[touchUI,setTouchUI]=useState(false),[joy,setJoy]=useState({x:0,y:0}),[stalk,setStalk]=useState(false),[savedMessage,setSavedMessage]=useState('');
 useEffect(()=>{let e:Engine;try{e=new Engine(mount.current!,map.current!,next=>{setS(next);if(next.dead){setJoy({x:0,y:0});joyPointer.current=null;burstPointer.current=null;setStalk(false)}},p=>{setPaused(p);if(p){setJoy({x:0,y:0});joyPointer.current=null;burstPointer.current=null;setStalk(false)}});engine.current=e;setQuality(e.quality);setTouchUI(matchMedia('(pointer:coarse)').matches);setReady(true)}catch(err){setError('The estuary could not start. Reload or try a recent browser.');console.error(err)}return()=>{e?.dispose();engine.current=null}},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.closest('input,[role="dialog"]'))return;const k=e.key.toLowerCase();if(k==='m'&&s.started){setBigMap(!bigMap);engine.current?.pause(!bigMap)}if(k==='h'){engine.current?.pause(true);setHelp(true)}if(k==='j'){engine.current?.pause(true);setJournal(true)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[s.started,bigMap]);
 useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<unknown>}}).modelContext;if(!ctx?.registerTool)return;const life=new AbortController();try{ctx.registerTool({name:'read_survival_status',description:'Read crocodile survival status, position and expedition progress.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({...engine.current?.state})},{signal:life.signal}).catch(()=>{})}catch{}return()=>life.abort()},[]);
 const open=(kind:'settings'|'help'|'journal')=>{if(s.started)engine.current?.pause(true);if(kind==='settings'){setQuality(engine.current?.quality||2);setSettings(true)};if(kind==='help')setHelp(true);if(kind==='journal')setJournal(true)};
 const close=(kind:'settings'|'help'|'journal')=>{if(kind==='settings')setSettings(false);if(kind==='help')setHelp(false);if(kind==='journal')setJournal(false);if(s.started&&!s.dead)engine.current?.pause(false)};
 const toggleMap=()=>{const value=!bigMap;setBigMap(value);if(s.started)engine.current?.pause(value)};
 const mute=()=>{const value=!muted;setMuted(value);engine.current?.setMuted(value)};
 const full=()=>{
  const d=document as unknown as {fullscreenElement?:Element;webkitFullscreenElement?:Element;documentElement:{requestFullscreen?:()=>Promise<void>;webkitRequestFullscreen?:()=>void};exitFullscreen?:()=>Promise<void>;webkitExitFullscreen?:()=>void};
  const isFull=Boolean(d.fullscreenElement||d.webkitFullscreenElement);
  if(!isFull){
   if(d.documentElement.requestFullscreen)d.documentElement.requestFullscreen().catch(()=>{});
   else if(d.documentElement.webkitRequestFullscreen)d.documentElement.webkitRequestFullscreen();
  }else{
   if(d.exitFullscreen)d.exitFullscreen().catch(()=>{});
   else if(d.webkitExitFullscreen)d.webkitExitFullscreen();
  }
 };
 const moveJoy=(e:ReactPointerEvent<HTMLDivElement>)=>{if(joyPointer.current!==e.pointerId)return;const r=e.currentTarget.getBoundingClientRect(),p=normalizeJoystick(e.clientX-r.left-r.width/2,e.clientY-r.top-r.height/2,45);setJoy(p);engine.current?.setJoystick(p)};
 const stopJoy=(e:ReactPointerEvent<HTMLDivElement>)=>{if(joyPointer.current!==e.pointerId)return;joyPointer.current=null;setJoy({x:0,y:0});engine.current?.setJoystick({x:0,y:0})};
 const stopBurst=(e:ReactPointerEvent<HTMLButtonElement>)=>{if(burstPointer.current===e.pointerId){burstPointer.current=null;if(engine.current)engine.current.touch.sprint=false}};
 const save=()=>{const ok=engine.current?.save();setSavedMessage(ok?'Saved on this device.':'Your browser could not save.');};
 const milestones=[{name:'Learn to hunt',detail:'Catch three fish in the shallows.',value:Math.min(3,s.fishCaught),max:3,icon:Fish},{name:'Claim the channel',detail:'Ambush a buffalo. Grab, drag, and roll.',value:Math.min(1,s.buffaloCaught),max:1,icon:Target},{name:'Know your territory',detail:'Discover three estuary landmarks.',value:Math.min(3,s.landmarks.length),max:3,icon:Compass},{name:'Become the apex',detail:'Feed and grow into a 40 ft river titan.',value:Math.floor(s.growth),max:100,icon:Leaf}];
 const activeGoal=milestones.find(m=>m.value<m.max)||{name:'The estuary is yours',detail:'Keep hunting, growing, and exploring.',value:1,max:1,icon:Check};
 const meters=[{name:'Vitality',value:s.health,icon:Heart,color:'health'},{name:'Nutrition',value:s.hunger,icon:Fish,color:'hunger'},{name:'Stamina',value:s.stamina,icon:Zap,color:'stamina'},{name:'Warmth',value:s.warmth,icon:Sun,color:'warmth'}];
 return <main className={`game-shell ${!s.started?'intro':''} ${touchUI?'touch-mode':''} ${s.mode==='DIVING'?'underwater':''}`}>
  <div ref={mount} className="world"/><div className="vignette"/>
  <header className="game-header">
   <div className="wordmark"><span className="brand-icon"><Waves size={23}/></span><span>SALTWATER<small>A LIFE IN THE ESTUARY</small></span></div>
   <div className="location"><span>{s.biome}</span><small>{s.time}<i/>{s.mode==='DIVING'?'BENEATH THE SURFACE':'OUTGOING TIDE'}</small></div>
   <div className="toolbar"><button onClick={mute} aria-label={muted?'Enable sound':'Mute sound'} title="Sound">{muted?<VolumeX size={18}/>:<Volume2 size={18}/>}</button><button onClick={toggleMap} aria-label="Estuary map" title="Map (M)"><Map size={18}/></button><button onClick={()=>open('journal')} aria-label="Expedition journal" title="Journal (J)"><BookOpen size={18}/></button><button onClick={()=>open('settings')} aria-label="Settings"><Settings2 size={18}/></button><button className="full-button" onClick={full} aria-label="Fullscreen" title="Fullscreen"><Maximize size={17}/></button>{s.started&&<button onClick={()=>engine.current?.pause(!paused)} aria-label={paused?'Resume game':'Pause game'}>{paused?<Play size={18}/>:<Pause size={18}/>}</button>}</div>
  </header>
   {!s.started&&<section className="start-screen"><div className="edition"><i/> A LIVING COASTAL WILDERNESS</div><h1>Saltwater<span>Instinct runs deep.</span></h1><p>Become the estuary’s apex predator. Slip through mangroves, stalk the shallows, and grow into a 40-foot titan of the wild.</p><div className="start-buttons"><Button className="primary-button" onClick={()=>engine.current?.start()} disabled={!ready||!!error}>{error?'Unable to start':ready?'Enter the estuary':'Growing the wilderness…'}<ChevronRight size={19}/></Button>{s.canContinue&&<button className="secondary-button" onClick={()=>engine.current?.continue()}><Play size={15}/> Continue expedition</button>}</div>{error&&<p className="error-message">{error}</p>}<div className="start-controls">{touchUI?<><span><Navigation size={15}/> Thumb to move</span><span><MousePointer2 size={15}/> Drag to look</span></>:<><span><kbd>W A S D</kbd> Move</span><span><MousePointer2 size={15}/> Look</span><span><kbd>F</kbd> Bite</span><span><kbd>Q</kbd> Tail</span><span><kbd>R</kbd> Roll</span><span><kbd>C</kbd> Dive</span></>}</div><button className="text-button" onClick={()=>open('help')}>Learn your instincts & controls <ChevronRight size={13}/></button><div className="edition-note"><span>PROCEDURAL WILDERNESS</span><i/><span>SINGLE PLAYER</span><i/><span>40 FT APEX TITAN</span></div></section>}
  {s.started&&!s.dead&&<>
   <div className="compass"><span>{Math.round(s.heading)}°</span><div><span>W</span><i/><span>N</span><b>◇</b><span>E</span><i/><span>S</span></div></div>
   <button className="field-notes" onClick={()=>open('journal')} aria-label="Open expedition milestones"><div className="eyebrow"><span className="short-line"/> YOUR EXPEDITION <ChevronRight size={13}/></div><h2>{activeGoal.name}</h2><p>{activeGoal.detail}</p><div className="goal-progress"><activeGoal.icon size={16}/><span>{activeGoal.value} / {activeGoal.max}{activeGoal.max===100?' GROWTH':''}</span><div className="small-track"><i style={{width:`${activeGoal.value/activeGoal.max*100}%`}}/></div></div><div className="growth-label"><Leaf size={13}/><span>{s.title.toUpperCase()}</span><b>{s.lengthFt} FT · {s.lengthM} M</b></div></button>
   {s.bossNear&&(()=>{
    const bossHpPct=Math.max(0,Math.min(100,(s.bossNear.hp/s.bossNear.maxHp)*100));
    return <div className={`boss-hud ${s.bossNear.dist<28?'in-combat':''}`} role="region" aria-label={`Apex Boss ${s.bossNear.name}`}>
     <div className="boss-hud-header">
      <div className="boss-hud-badge"><Skull size={13}/><span>APEX BOSS</span></div>
      <div className="boss-hud-title">
       <span className="boss-title-prefix">{s.bossNear.title.toUpperCase()}</span>
       <span className="boss-title-name">{s.bossNear.name}</span>
      </div>
      <div className="boss-hud-dist"><Crosshair size={12}/><span>{s.bossNear.dist}m</span></div>
     </div>
     <div className="boss-bar-wrap">
      <div className="boss-bar-track" role="progressbar" aria-label={`${s.bossNear.name} Health`} aria-valuenow={s.bossNear.hp} aria-valuemin={0} aria-valuemax={s.bossNear.maxHp}>
       <div className="boss-bar-fill" style={{width:`${bossHpPct}%`}}/>
       <div className="boss-bar-glow" style={{left:`${bossHpPct}%`}}/>
       <div className="boss-bar-segments"><i/><i/><i/><i/></div>
      </div>
      <div className="boss-hp-numbers">
       <span>{s.bossNear.hp} / {s.bossNear.maxHp} HP</span>
       <b>{Math.round(bossHpPct)}%</b>
      </div>
     </div>
    </div>;
   })()}
   {s.waypoint&&<div className="waypoint"><Navigation size={14} style={{transform:`rotate(${-s.waypointBearing-45}deg)`}}/><span>{s.waypoint}</span><b>{Math.round(s.waypointDistance)} m</b></div>}
   <div className={`prey-hint ${s.grip>0?'grappling':''}`}>{s.grip>0?<><Anchor size={15}/><span>{s.rolling?'DEATH ROLL IN PROGRESS':s.target.includes('JAW LOCK')?'RIVAL JAW LOCK':'HOLDING BUFFALO'}</span><div className="grip-track"><i style={{width:`${s.grip}%`}}/></div><kbd>R</kbd><span>Roll</span></>:s.meal?<><Fish size={15}/><span>{s.feeding?'Feeding…':'Your catch is ready'}</span><kbd>E</kbd><span>Feed</span></>:s.basking?<><Sun size={15}/><span>Basking · plovers cleaning teeth · healing</span></>:s.target?<><span className={`target-dot ${s.awareness>.55?'alert':''}`}/><span>{s.target}</span><span className="awareness">{s.canBite?'BITE NOW':s.awareness>.55?'FLEEING':s.awareness>.2?'ALERT':'UNAWARE'}</span></>:s.rivalNear?<><span className="target-dot alert"/><span>{s.rivalNear}</span><span className="awareness alert">CAUTION</span></>:<span className="quiet">Move with the river.</span>}</div>
   <section className="survival-hud" aria-label="Survival statistics"><div className="croc-id"><span>CROCODYLUS POROSUS</span><span>{s.basking?'BASKING':s.mode} · {(s.speed*3.6).toFixed(1)} KM/H</span></div><div className="meters">{meters.map(m=><div className={`meter ${m.color} ${m.value<20?'low':''}`} key={m.name}><div className="meter-label"><m.icon size={14}/><span>{m.name}</span><b>{Math.round(m.value)}<small>%</small></b></div><div className="meter-track" role="progressbar" aria-label={m.name} aria-valuenow={Math.round(m.value)} aria-valuemin={0} aria-valuemax={100}><i style={{width:`${m.value}%`}}/></div></div>)}</div>{s.mode==='DIVING'&&<div className="air-meter"><Wind size={14}/><span>AIR</span><div className="meter-track" role="progressbar" aria-label="Oxygen" aria-valuenow={Math.round(s.air)} aria-valuemin={0} aria-valuemax={100}><i style={{width:`${s.air}%`}}/></div><b>{Math.round(s.air)}%</b><span>{s.depth.toFixed(1)} M</span></div>}</section>
   <div className="desktop-actions"><button disabled={s.rolling} onClick={()=>engine.current?.attack()} title="Bite / Jaw Clamp (F)"><kbd>F</kbd><span>Bite</span></button><button disabled={s.rolling} onClick={()=>engine.current?.tailWhip()} title="Tail Whip Knockback (Q)"><kbd>Q</kbd><span>Tail</span></button><button className={s.grip>0?'roll-ready':''} onClick={()=>engine.current?.roll()} disabled={!s.grip||s.rolling} title="Death Roll in Water (R)"><kbd>R</kbd><span>{s.rolling?'Rolling':'Roll'}</span></button><button onClick={()=>engine.current?.dive()} title="Dive / Rise (C)"><kbd>C</kbd><span>{s.mode==='DIVING'?'Rise':'Dive'}</span></button><button disabled={s.rolling} onClick={()=>engine.current?.interact()} title="Feed / Bask / Release (E)"><kbd>E</kbd><span>{s.grip>0?'Release':s.meal?'Feed':'Bask'}</span></button><button onClick={()=>engine.current?.resetCamera()} title="Reset Camera Behind Croc (V)"><kbd>V</kbd><span>Cam</span></button></div>
   <div className="quick-controls"><span><kbd>W A S D</kbd> Move</span><span><kbd>SHIFT</kbd> Burst</span><span><kbd>CTRL</kbd> Stalk</span><span><kbd>V</kbd> Cam</span><span>Drag to look · Scroll to zoom</span><button onClick={()=>open('help')}><HelpCircle size={14}/> Controls</button></div>
   <div className="mobile-controls" aria-label="Touch controls"><div className="joystick-area"><div className="joystick" role="group" aria-label="Movement joystick" onPointerDown={e=>{if(joyPointer.current!==null)return;joyPointer.current=e.pointerId;e.currentTarget.setPointerCapture(e.pointerId);moveJoy(e)}} onPointerMove={moveJoy} onPointerUp={stopJoy} onPointerCancel={stopJoy} onLostPointerCapture={stopJoy}><i className="joystick-ring"/><span className="joystick-knob" style={{transform:`translate(${joy.x*39}px,${joy.y*39}px)`}}><Navigation size={20}/></span></div><span className="joystick-caption">MOVE</span><button className={stalk?'stalk active':'stalk'} onClick={()=>{const v=!stalk;setStalk(v);if(engine.current)engine.current.touch.stalk=v}}>{stalk?'Stalking':'Stalk'}</button></div><div className="mobile-actions"><button className="burst-action" aria-label="Hold to burst" onPointerDown={e=>{if(burstPointer.current!==null)return;burstPointer.current=e.pointerId;e.currentTarget.setPointerCapture(e.pointerId);if(engine.current)engine.current.touch.sprint=true}} onPointerUp={stopBurst} onPointerCancel={stopBurst} onLostPointerCapture={stopBurst}><ChevronsUp size={19}/><span>Burst</span></button><button disabled={s.rolling} onClick={()=>engine.current?.dive()} aria-label={s.mode==='DIVING'?'Rise to surface':'Dive underwater'}><Waves size={19}/><span>{s.mode==='DIVING'?'Rise':'Dive'}</span></button><button disabled={s.rolling||!s.grip} className={`roll-action ${s.grip>0?'roll-ready':''}`} onClick={()=>engine.current?.roll()} aria-label="Death roll in water"><RotateCcw size={19}/><span>{s.rolling?'Rolling':'Roll'}</span></button><button disabled={s.rolling} onClick={()=>engine.current?.tailWhip()} aria-label="Tail whip knockback"><Shield size={19}/><span>Tail</span></button><button disabled={s.rolling} onClick={()=>engine.current?.interact()} aria-label="Interact or feed"><ActionIcon grip={s.grip} meal={!!s.meal}/><span>{s.grip?'Release':s.meal?'Feed':'Bask'}</span></button><button disabled={s.rolling} className="bite-action" onClick={()=>engine.current?.attack()} aria-label="Bite prey"><Target size={25}/><span>BITE</span></button></div><span className="touch-look-hint">DRAG THE WORLD TO LOOK</span></div>
  </>}
  <aside className={`mini-map ${bigMap?'expanded':''} ${!s.started&&!bigMap?'intro-map':''}`} aria-label="Estuary map"><div className="map-title"><span><Compass size={14}/> THE ESTUARY</span><button onClick={toggleMap} aria-label={bigMap?'Close map':'Expand map'}>{bigMap?<X size={18}/>:<Maximize size={13}/>}</button></div><div className="map-wrap"><canvas width="256" height="256" ref={map} aria-label="Estuary map with your position, nearby wildlife and landmarks"/><span className="map-north">N</span><span className="map-scale">500 M</span></div><div className="map-footer"><span>2 × 2 KM</span><span>{Math.round(s.distance)} M EXPLORED</span></div>{bigMap&&<><p className="map-instruction">Choose a landmark to navigate toward it.</p><div className="landmark-list">{LANDMARKS.map(l=><button key={l.id} onClick={()=>engine.current?.waypoint(l.id)} className={s.waypoint===l.name?'selected':''}><span>{s.landmarks.includes(l.id)?<Check size={14}/>:<Navigation size={14}/>} {l.name}</span><span>{Math.round(Math.hypot(l.x-s.x,l.z-s.z))} m</span></button>)}</div><div className="map-legend"><span>▲ You</span><span>• Nearby wildlife</span><span>◆ Landmarks</span></div></>}</aside>
  {bigMap&&<button className="map-backdrop" aria-label="Close estuary map" onClick={toggleMap}/>}
  {s.message&&s.started&&!paused&&!s.dead&&<output className="notification" aria-live="polite">{s.message}</output>}
  {paused&&s.started&&!settings&&!help&&!journal&&!bigMap&&!s.dead&&<div className="pause-screen"><div className="pause-card"><div className="eyebrow">A MOMENT OF STILLNESS</div><h2>The wild can wait.</h2><p>Your expedition is paused.</p><Button className="primary-button" onClick={()=>engine.current?.pause(false)}><Play size={17}/> Return to the estuary</Button><button className="save-button" onClick={save}><Save size={16}/> Save on this device</button>{savedMessage&&<p className="saved-message" role="status">{savedMessage}</p>}<div className="pause-options"><button onClick={()=>open('help')}>Controls</button><button onClick={()=>open('settings')}>Settings</button><button onClick={()=>{setStalk(false);engine.current?.restart()}}>New expedition</button></div></div></div>}
  {s.dead&&<div className="pause-screen"><div className="pause-card"><div className="eyebrow">THE CYCLE CONTINUES</div><h2>The wild takes its toll.</h2><p>{s.kills} prey caught · {Math.round(s.distance)} metres explored<br/>{s.landmarks.length} landmarks discovered</p><Button className="primary-button" onClick={()=>engine.current?.restart()}><RotateCcw size={17}/> Begin a new life</Button>{s.canContinue&&<button className="save-button" onClick={()=>engine.current?.continue()}>Continue your saved expedition</button>}</div></div>}
  <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="game-dialog"><DialogHeader><DialogTitle>Make yourself at home.</DialogTitle><DialogDescription>Find the right feel for your device.</DialogDescription></DialogHeader><div className="setting"><label>Graphics</label><div className="quality-options">{[1,2,3].map((q,i)=><button key={q} className={quality===q?'selected':''} onClick={()=>{setQuality(q);engine.current?.setQuality(q)}}>{['Performance','Balanced','Cinematic'][i]}</button>)}</div><p>Performance suits phones. Balanced adds soft shadows; Cinematic extends the view.</p></div><div className="setting-row"><div><label htmlFor="audio">Estuary sound</label><p>Tribal jungle music, ambient wildlife, and hunting instincts.</p></div><Switch id="audio" checked={!muted} onCheckedChange={v=>{setMuted(!v);engine.current?.setMuted(!v)}}/></div><div className="setting-row"><div><label htmlFor="touch">Touch controls</label><p>Joystick and action buttons. Also useful on tablets.</p></div><Switch id="touch" checked={touchUI} onCheckedChange={v=>{setTouchUI(v);engine.current?.clearInput();setJoy({x:0,y:0});setStalk(false)}}/></div><div className="sensitivity"><div><label>Camera sensitivity</label><b>{sens.toFixed(1)}×</b></div><Slider min={.3} max={2} step={.1} value={[sens]} onValueChange={v=>{setSens(v[0]);if(engine.current)engine.current.sensitivity=v[0]}} aria-label="Camera sensitivity"/></div><p className="performance">{s.fps} FPS · {s.quality}{s.renderer==='Compatibility'?' · Reduced-detail compatibility rendering':''}</p><Button className="primary-button" onClick={()=>close('settings')}>{s.started?'Return to the wild':'Done'}</Button></DialogContent></Dialog>
   <Dialog open={help} onOpenChange={setHelp}><DialogContent className="game-dialog controls-dialog"><DialogHeader><DialogTitle>Trust your instincts.</DialogTitle><DialogDescription>Quiet movement brings you closer. Aim your snout at prey.</DialogDescription></DialogHeader><div className="control-grid">{[['W A S D / arrows','Move and turn'],['Drag / scroll','Look around / zoom'],['Shift / Ctrl','Burst / stalk'],['F / left click','Bite · Jaw clamp · Jaw clash'],['Q','Tail whip knockback'],['R','Death roll (water only)'],['C / Space','Dive / rise'],['E','Feed carcass · Bask · Release'],['B','Bask on dry bank'],['V','Reset chase camera'],['M / J / Esc','Map / journal / pause']].map(([k,v])=><div key={k}><kbd>{k}</kbd><span>{v}</span></div>)}</div><div className="survival-tip"><h3>Combat & Hunting Moves</h3><p>Bite fish and crabs for quick nourishment. Ambush buffalo drinking at the bank or swimming across the river: clamp down with F, drag them into the channel, and trigger R for the Death Roll. Against rival predators: use Q (Tail Whip) to stagger and knock them back, engage in head-on Jaw Clash battles, and tear them apart with Death Roll when in water!</p><h3>Apex Boss Encounters</h3><p>As you grow from a 5 ft yearling to a 40 ft sovereign titan, formidable world bosses awaken across the estuary: the Megatooth Bull Shark (growth 25+), Goliath Hippo Patriarch (growth 50+), Dreadmaw Behemoth (growth 65+), and Sovereign Brutus, the 42 ft swamp tyrant (growth 90+). Defeating an apex boss yields +30 growth and 8 full servings of nourishment!</p><h3>Basking & Health</h3><p>Rest on dry sandbanks with B or E to bask. Plovers land to clean your teeth and accelerate health recovery. Dive with C to stalk prey unseen beneath the surface.</p></div><Button className="primary-button" onClick={()=>close('help')}>{s.started?'Back to the hunt':'Ready to explore'}</Button></DialogContent></Dialog>
  <Dialog open={journal} onOpenChange={setJournal}><DialogContent className="game-dialog journal-dialog"><DialogHeader><DialogTitle>Your life in the estuary.</DialogTitle><DialogDescription>An open wilderness. These milestones give your expedition a direction.</DialogDescription></DialogHeader><div className="journal-milestones">{milestones.map(m=><div key={m.name} className={m.value>=m.max?'complete':''}><span className="milestone-icon">{m.value>=m.max?<Check size={19}/>:<m.icon size={19}/>}</span><div><h3>{m.name}</h3><p>{m.detail}</p></div><b>{m.value} / {m.max}</b></div>)}</div><div className="journal-stats"><span><b>{s.kills}</b> prey caught</span><span><b>{s.regions}</b> habitats</span><span><b>{Math.round(s.distance)}</b> metres</span></div><p className="performance">Your progress stays in this expedition. Use “Save on this device” from the pause screen to return later in the same browser.</p><Button className="primary-button" onClick={()=>close('journal')}>{s.started?'Return to the estuary':'Done'}</Button></DialogContent></Dialog>
  <span className="version">SALTWATER / 0.4 · 40 FT TITAN</span>
 </main>;
}
function ActionIcon({grip,meal}:{grip:number;meal?:boolean}){return grip?<Anchor size={19}/>:meal?<Fish size={19}/>:<Sun size={19}/>}
