import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import ts from 'typescript';
const out=path.resolve('.sites-runtime/gameplay-tests');fs.mkdirSync(out,{recursive:true});
for(const name of ['audio','batching','input','storage','materials','water-props','world','habitat','motion','geometry','crocodile','models','software-renderer','engine']){const src=fs.readFileSync(`lib/game/${name}.ts`,'utf8');const compiled=ts.transpileModule(src,{compilerOptions:{module:ts.ModuleKind.ES2022,target:ts.ScriptTarget.ES2022}}).outputText.replace(/from '(\.\/[^']+)'/g,"from '$1.js'");fs.writeFileSync(`${out}/${name}.js`,compiled)}
const {validHabitat}=await import(`${out}/habitat.js`);const {rollPose,ROLL_DURATION}=await import(`${out}/motion.js`);const {PAD_CLEARANCE}=await import(`${out}/water-props.js`);
const {Engine,initial}=await import(`${out}/engine.js`);const {heightAt,riverCenter,HALF,EstuaryWorld,LANDMARKS}=await import(`${out}/world.js`);const {crocodile,fish,buffalo,rivalCroc}=await import(`${out}/models.js`);const {normalizeJoystick,joystickHeading,angleDelta}=await import(`${out}/input.js`);const {validateSave}=await import(`${out}/storage.js`);const T=await import('three');
function game(){const e=Object.create(Engine.prototype);Object.assign(e,{state:{...initial,started:true,landmarks:[]},scene:new T.Scene(),croc:crocodile(),world:{obstacles:[],update(){}},animals:[],rivals:[],plovers:[],waders:[],keys:new Set(),touch:{joystick:{x:0,y:0},sprint:false,stalk:false},started:true,paused:false,dead:false,diving:false,speed:0,time:0,yaw:0,pitch:.35,regions:new Set(['MANGROVE REACH']),biteTimer:0,attackCooldown:0,rollTimer:0,rollVictim:null,rollSplash:0,feedingTimer:0,messageTimer:0,damageCooldown:0,particles:[],audio:null,fpsSamples:[60],renderer:{info:{render:{calls:0}},domElement:{focus(){}}},onUpdate(){},onPause(){},cameraPointer:null,cameraIdle:0,turnAmount:0,grip:0,grabbed:null,basking:false,waypointId:'',wakeTimer:0,saved:null});e.croc.root.position.set(riverCenter(0),-.12,0);return e}
function prey(e,kind,z=-3){const root=kind==='buffalo'?buffalo():fish();root.position.set(e.croc.root.position.x,kind==='buffalo'?.1:-.8,z);const a={root,kind,alive:true,hp:kind==='buffalo'?3:1,home:root.position.clone(),angle:0,phase:0,respawn:0,flee:0,awareness:0,velocity:0,servings:0};e.animals.push(a);return a}
globalThis.document={pointerLockElement:null};globalThis.performance={now:()=>0};let deviceSave=null;globalThis.localStorage={getItem(){return deviceSave},setItem(_key,v){deviceSave=v}};const run=(e,seconds)=>{for(let i=0;i<Math.ceil(seconds*60)&&!e.dead;i++){e.time+=1/60;e.step(1/60)}};
const results=[];function test(name,fn){fn();results.push(name);console.log('PASS',name)}
test('Two-kilometre world has water, continuous banks and walkable forest terrain',()=>{let land=0,water=0,deep=0,maxSlope=0;for(let z=-990;z<990;z+=8)for(let x=-990;x<990;x+=8){const h=heightAt(x,z);if(h>0)land++;else water++;if(h<-3)deep++;maxSlope=Math.max(maxSlope,Math.abs(heightAt(x+.1,z)-h)/.1)}assert.ok(land>1000&&water>1000&&deep>1000);assert.ok(maxSlope<1.8)});
test('Terrain chunks are bounded and unloaded while roaming',()=>{const w=new EstuaryWorld(new T.Scene());w.update(0,0,0,2);assert.equal(w.chunks.size,25);w.update(700,700,0,2);assert.equal(w.chunks.size,25);assert.ok([...w.chunks.keys()].every(k=>Number(k.split(':')[0])>=5));w.update(700,700,0,3);assert.ok(w.chunks.size<=49);w.dispose()});
test('Swimming accelerates and decelerates smoothly',()=>{const e=game();e.keys.add('w');run(e,5);assert.ok(e.state.distance>19);assert.equal(e.state.mode,'SWIMMING');e.keys.clear();run(e,3);assert.ok(e.state.speed<.01)});
test('Skeleton weights are normalized and tail vertices actually deform',()=>{const c=crocodile(),weights=c.skin.geometry.attributes.skinWeight;for(let i=0;i<weights.count;i++)assert.ok(Math.abs(weights.getX(i)+weights.getY(i)-1)<.00001);const index=c.skin.geometry.attributes.position.count-12,before=c.skin.getVertexPosition(index,new T.Vector3());c.animate(.6,3,true,0,0);c.root.updateMatrixWorld(true);c.skin.skeleton.update();const after=c.skin.getVertexPosition(index,new T.Vector3());assert.ok(before.distanceTo(after)>.02)});
test('All four legs articulate on land',()=>{const c=crocodile();c.animate(.6,2,false,0,0);assert.ok(c.legs.every(l=>Math.abs(l.rotation.y)>.01));assert.ok(c.knees.some(l=>Math.abs(l.rotation.x)>.01))});
test('Land movement follows the bank surface',()=>{const e=game();e.croc.root.position.set(100,heightAt(100,0),0);e.keys.add('w');run(e,4);assert.equal(e.state.mode,'LAND');assert.ok(Math.abs(e.croc.root.position.y-heightAt(e.state.x,e.state.z)-.035)<.04)});
test('Burst drains stamina; rest restores it',()=>{const e=game();e.keys.add('w');e.keys.add('shift');run(e,3);assert.ok(e.state.stamina<67);e.keys.clear();run(e,4);assert.ok(e.state.stamina>95)});
test('Dive consumes air; surface restores it',()=>{const e=game();e.dive();run(e,10);assert.equal(e.state.mode,'DIVING');assert.ok(e.state.air<88);e.keys.add(' ');run(e,3);assert.equal(e.state.mode,'SWIMMING');assert.equal(e.state.air,100)});
test('Bite captures small prey, grants nutrition and growth',()=>{const e=game(),a=prey(e,'fish');e.attack();assert.equal(e.state.fishCaught,1);assert.equal(e.state.kills,1);assert.equal(e.state.growth,8);assert.equal(e.state.hunger,84);assert.equal(a.alive,false)});
test('Bite cooldown prevents duplicate captures',()=>{const e=game();prey(e,'fish');prey(e,'fish',-4);e.attack();e.attack();assert.equal(e.state.kills,1)});
test('Buffalo grab, water roll, carcass and feeding form a full hunt',()=>{const e=game(),a=prey(e,'buffalo');e.attack();assert.equal(e.grabbed,a);assert.equal(e.grip,100);assert.equal(e.state.health,96);run(e,.2);e.roll();assert.equal(a.alive,true);assert.equal(e.state.buffaloCaught,0);run(e,ROLL_DURATION+.05);assert.equal(e.state.buffaloCaught,1);assert.equal(e.grabbed,null);assert.equal(a.servings,3);const before=e.state.hunger;e.interact();assert.equal(a.servings,2);assert.ok(e.state.hunger>before);assert.equal(e.state.growth,9);e.interact();assert.equal(a.servings,2)});
test('Release and timed escape end a grapple',()=>{const e=game(),a=prey(e,'buffalo');e.attack();e.interact();assert.equal(e.grabbed,null);e.attackCooldown=0;e.attack();e.grip=.01;run(e,.1);assert.equal(e.grabbed,null);assert.ok(a.flee>0)});
test('Stalking causes less prey awareness than charging',()=>{const slow=game(),fast=game();slow.croc.root.position.x=46;fast.croc.root.position.x=46;const a=prey(slow,'buffalo',-12),b=prey(fast,'buffalo',-12);slow.speed=1;fast.speed=4;for(let i=0;i<45;i++){slow.stepAnimals(1/60,true,true);fast.stepAnimals(1/60,false,true)}assert.ok(a.awareness<b.awareness);assert.ok(b.awareness>.5)});
test('Fish remain above their actual terrain even when blocked at shore',()=>{const e=game(),a=prey(e,'fish');a.root.position.set(35,-.8,0);a.angle=Math.PI/2;a.velocity=3;a.awareness=1;run(e,2);assert.ok(a.root.position.y>=heightAt(a.root.position.x,a.root.position.z)+.3)});
test('Basking on a dry bank restores warmth and healing',()=>{const e=game();e.croc.root.position.set(100,heightAt(100,0),0);e.state.warmth=40;e.state.health=75;e.bask();run(e,5);assert.equal(e.state.basking,true);assert.ok(e.state.warmth>41);assert.ok(e.state.health>77);e.keys.add('w');run(e,.1);assert.equal(e.state.basking,false)});
test('Starvation ends the expedition; restart clears transient hunting state',()=>{const e=game();e.diving=true;e.state.air=0;e.state.health=1;run(e,1);assert.equal(e.dead,true);e.restart();assert.equal(e.dead,false);assert.equal(e.state.health,100);assert.equal(e.state.kills,0);assert.equal(e.grabbed,null);assert.equal(e.rollTimer,0)});
test('Pause clears movement, burst and camera pointer',()=>{const e=game();e.keys.add('w');e.touch.joystick={x:1,y:1};e.touch.sprint=true;e.cameraPointer=5;e.pause();assert.equal(e.keys.size,0);assert.equal(e.touch.sprint,false);assert.equal(e.cameraPointer,null);assert.deepEqual(e.touch.joystick,{x:0,y:0})});
test('World edge and trunks prevent penetration',()=>{const e=game();e.croc.root.position.set(0,heightAt(0,-HALF+11),-HALF+11);e.keys.add('w');run(e,8);assert.ok(e.croc.root.position.z>=-HALF+10);const e2=game();e2.croc.root.position.set(100,heightAt(100,0),0);e2.world.obstacles=[{x:100,z:-2,r:.7}];e2.keys.add('w');run(e2,4);assert.ok(e2.croc.root.position.z>-1)});
test('Joystick is normalized, has a dead zone, and follows camera heading',()=>{assert.deepEqual(normalizeJoystick(1,1),{x:0,y:0});const j=normalizeJoystick(100,-100,45);assert.ok(Math.abs(Math.hypot(j.x,j.y)-1)<.0001);assert.equal(joystickHeading({x:0,y:-1},.5),.5);const e=game();e.yaw=Math.PI/2;e.touch.joystick={x:0,y:-1};run(e,3);assert.ok(Math.abs(angleDelta(e.croc.root.rotation.y,Math.PI/2))<.1);assert.ok(e.state.x<-5)});
test('Landmarks are discovered and waypoints report distance',()=>{const e=game(),l=LANDMARKS[0];e.waypoint(l.id);e.croc.root.position.set(l.x,heightAt(l.x,l.z),l.z);run(e,.1);assert.ok(e.state.landmarks.includes(l.id));assert.equal(e.state.waypointDistance,0)});
test('Device save round-trips progress and rejects corrupt or out-of-world data',()=>{const e=game();e.state.kills=3;e.state.growth=24;assert.equal(e.save(),true);const s=JSON.parse(deviceSave);assert.ok(validateSave(s));assert.equal(validateSave({...s,x:9000}),null);assert.equal(validateSave({...s,growth:NaN}),null);e.state.kills=0;e.continue();assert.equal(e.state.kills,3);assert.equal(e.state.growth,24);assert.equal(e.diving,false)});
test('Crocodile body normals face outward for back-face culling',()=>{const c=crocodile(),p=c.skin.geometry.attributes.position,n=c.skin.geometry.attributes.normal;let positive=0;for(let i=0;i<p.count;i++)if(p.getX(i)*n.getX(i)>0)positive++;assert.ok(positive>p.count*.7)});
test('Every buffalo and crab spawn has a dry footprint through a full tide cycle',()=>{const e=game();e.populate();assert.equal(e.animals.filter(a=>a.kind==='buffalo').length,22);assert.equal(e.animals.filter(a=>a.kind==='crab').length,32);for(const a of e.animals.filter(a=>a.kind!=='fish')){for(const tide of [-.16,0,.16])assert.ok(validHabitat(a.kind,a.home.x,a.home.z,tide),`${a.kind} home is flooded`);assert.ok(a.home.y>=.28)}});
test('Lagoon wildlife recovers invalid placement and fleeing never crosses a flooded bank',()=>{const e=game(),a=prey(e,'buffalo');a.root.position.set(125,-8,225);a.home.copy(a.root.position);e.croc.root.position.set(140,-.12,225);e.stepAnimals(1/60,false,true);assert.ok(validHabitat('buffalo',a.root.position.x,a.root.position.z));assert.equal(a.root.position.y,heightAt(a.root.position.x,a.root.position.z));a.awareness=1;a.flee=20;for(let i=0;i<1200;i++){e.time+=1/60;e.stepAnimals(1/60,false,true);assert.ok(validHabitat('buffalo',a.root.position.x,a.root.position.z))}});
test('Buffalo respawns retain a dry home and carcasses rest on top of dry terrain',()=>{const e=game();e.populate();const a=e.animals.find(a=>a.kind==='buffalo');a.alive=false;a.servings=3;a.respawn=10;a.root.rotation.z=Math.PI/2;const h=heightAt(a.root.position.x,a.root.position.z);e.stepAnimals(1/60,false,true);assert.ok(a.root.position.y>=h+.68);a.respawn=-1;e.croc.root.position.set(800,3,800);e.stepAnimals(1/60,false,false);assert.equal(a.alive,true);assert.ok(validHabitat('buffalo',a.root.position.x,a.root.position.z,.16));assert.equal(a.root.rotation.z,0)});
test('Lily pads stay above the water at low and high tide without reloading chunks',()=>{const w=new EstuaryWorld(new T.Scene());w.update(125,225,0,2);const first=[...w.chunks.values()].filter(c=>c.floaters);assert.ok(first.length>3);for(const t of [0,Math.PI*65,Math.PI*195,700]){w.update(125,225,t,2);for(const chunk of first){assert.ok(Math.abs(chunk.floaters.position.y-w.water.position.y-PAD_CLEARANCE)<.00001);const m=new T.Matrix4();for(let i=0;i<chunk.floaters.count;i++){chunk.floaters.getMatrixAt(i,m);const n=new T.Vector3(0,1,0).transformDirection(m);assert.ok(n.y>.9999);assert.equal(m.elements[13],0)}}}w.update(700,700,Math.PI*65,3);for(const c of w.chunks.values())if(c.floaters)assert.ok(c.floaters.position.y>w.water.position.y);w.dispose()});
test('Front feet have five digits, hind feet four, with three claws and hind webbing',()=>{const c=crocodile();assert.deepEqual(c.digits.map(d=>d.length),[5,5,4,4]);assert.ok(c.digits.every(d=>d.filter(t=>t.userData.clawed).length===3));assert.equal(c.webs.length,2);assert.ok(c.webs.every(w=>w.parent.name==='webbed_hind_foot'));assert.equal(c.claws.length,12)});
test('Slow swimming moves all four limbs and ankles; fast swimming folds the limbs back',()=>{const c=crocodile();for(let i=0;i<90;i++)c.animate(i/60,1.3,true,0,0);c.root.updateMatrixWorld(true);const before=c.feet.map(f=>f.getWorldPosition(new T.Vector3()));const ankle=c.feet.map(f=>f.rotation.x);for(let i=90;i<126;i++)c.animate(i/60,1.3,true,0,0);c.root.updateMatrixWorld(true);assert.ok(c.feet.every((f,i)=>f.getWorldPosition(new T.Vector3()).distanceTo(before[i])>.02));assert.ok(c.feet.every((f,i)=>Math.abs(f.rotation.x-ankle[i])>.015));for(let i=126;i<250;i++)c.animate(i/60,8.6,true,0,0);assert.ok(c.legs.every(l=>Math.abs(l.rotation.y)>.7));assert.ok(c.feet.every(f=>Number.isFinite(f.rotation.x)))});
test('Water-to-land animation blends without a one-frame pose jump',()=>{const c=crocodile();for(let i=0;i<100;i++)c.animate(i/60,2,true,0,0);const old=c.legs.map(l=>l.quaternion.clone());c.animate(100/60,2,false,0,0);assert.ok(c.legs.every((l,i)=>l.quaternion.angleTo(old[i])<.2))});
test('Death roll winds up, keeps prey held, blocks interruption and kills at recovery',()=>{const e=game(),a=prey(e,'buffalo');e.attack();run(e,.2);e.roll();assert.equal(a.alive,true);assert.equal(e.state.kills,0);assert.ok(rollPose(ROLL_DURATION-.08).angle<.02);run(e,.7);assert.equal(e.grabbed,a);assert.equal(a.alive,true);assert.ok(Math.abs(e.croc.body.rotation.z)>1);assert.ok(e.croc.legs.every(l=>Math.abs(l.rotation.y)>.6));const hp=a.hp;e.attack();e.interact();assert.equal(a.hp,hp);assert.equal(e.grabbed,a);run(e,1);assert.equal(a.alive,false);assert.equal(e.rollVictim,null);assert.equal(e.state.kills,1);assert.ok(Math.abs(e.croc.body.rotation.z)<.001)});
test('A roll cannot consume stamina on dry land or without a victim',()=>{const e=game();e.roll();assert.equal(e.state.stamina,100);const a=prey(e,'buffalo');e.grabbed=a;e.grip=90;e.croc.root.position.set(100,heightAt(100,0),0);e.roll();assert.equal(e.rollTimer,0);assert.equal(e.state.stamina,100);assert.ok(e.state.message.includes('deeper water'))});
test('Buffalo river crossing does not disappear when approached by crocodile in water',()=>{const e=game(),a=prey(e,'buffalo');const riverX=riverCenter(30);a.root.position.set(riverX,-1.2,30);a.crossing=true;a.crossTarget={x:riverX+40,z:30};e.croc.root.position.set(riverX-4,-.12,30);for(let i=0;i<60;i++){e.time+=1/60;e.stepAnimals(1/60,false,true);}assert.equal(a.root.visible,true);assert.ok(a.root.position.x>riverX-2);});
test('Defeated rival crocodile body disappears after consuming all servings',()=>{const e=game(),croc=rivalCroc();const r={root:croc.root,kind:'croc',name:'Old Scarface Bull',alive:false,hp:0,maxHp:10,home:new T.Vector3(0,0,0),territoryRadius:40,angle:0,phase:0,respawn:180,velocity:0,servings:1,warningTimer:0,attackCooldown:0};e.rivals.push(r);e.croc.root.position.set(0,-.12,2);r.root.position.set(0,-.12,0);e.stepRivals(1/60,false,true);assert.equal(r.root.visible,true);e.interact();assert.equal(r.servings,0);assert.equal(r.root.visible,false);e.stepRivals(1/60,false,true);assert.equal(r.root.visible,false);});
test('Crocodile bodies push apart and do not merge during combat collision',()=>{const e=game(),croc=rivalCroc();const r={root:croc.root,kind:'croc',name:'Dominant Bull',alive:true,hp:10,maxHp:10,home:new T.Vector3(0,0,0),territoryRadius:40,angle:0,phase:0,respawn:0,velocity:2,servings:0,warningTimer:0,attackCooldown:0};e.rivals.push(r);e.croc.root.position.set(0,-.12,1.2);r.root.position.set(0,-.12,0);const beforeDist=e.croc.root.position.distanceTo(r.root.position);assert.ok(beforeDist<2.0);e.step(1/60);const afterDist=e.croc.root.position.distanceTo(r.root.position);assert.ok(afterDist>beforeDist);assert.ok(afterDist>=3.5);});
console.log(JSON.stringify({passed:results.length,failed:0,tests:results},null,2));
