import * as T from 'three';
import {lilyPadGeometry,lotusFlowerGeometry,PAD_CLEARANCE} from './water-props';
import {terrainMaterial,barkMaterial} from './materials';
export const WORLD_SIZE=2000,HALF=WORLD_SIZE/2,WATER=0,CHUNK=100;
export const LANDMARKS=[{id:'jetty',name:'The Old Jetty',x:18,z:-30,description:'Weathered timber at the edge of the river.'},{id:'lagoon',name:'Stillwater Bend',x:160,z:355,description:'A quiet lagoon rich with fish.'},{id:'grasslands',name:'Buffalo Crossing',x:170,z:490,description:'Herds drink at the floodplain.'},{id:'coast',name:'The Tidal Wreck',x:-160,z:-587,description:'A forgotten boat above the salt coast.'},{id:'rainforest',name:'The Ancient Fig',x:-450,z:50,description:'A sheltered place deep in the forest.'}];
export function seeded(seed:number){return()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}}
function hash(x:number,z:number){let n=(Math.imul(x|0,374761393)^Math.imul(z|0,668265263))>>>0;n=Math.imul(n^(n>>>13),1274126177);return((n^(n>>>16))>>>0)/4294967295}
export function noise(x:number,z:number){const ix=Math.floor(x),iz=Math.floor(z);let fx=x-ix,fz=z-iz;fx=fx*fx*(3-2*fx);fz=fz*fz*(3-2*fz);return T.MathUtils.lerp(T.MathUtils.lerp(hash(ix,iz),hash(ix+1,iz),fx),T.MathUtils.lerp(hash(ix,iz+1),hash(ix+1,iz+1),fx),fz)}
export function riverCenter(z:number){return 42*Math.sin(z*.008)+22*Math.sin(z*.017)}
export function channelDistance(x:number,z:number){const river=Math.abs(x-riverCenter(z))-(38+12*Math.sin(z*.005));const lagoon=Math.hypot((x-125)*.85,z-225)-132;const tributary=Math.abs(z-440-42*Math.sin(x*.013))-20;return Math.min(river,lagoon,tributary,z+610)}
export function heightAt(x:number,z:number){const d=channelDistance(x,z);let h=d<0?Math.max(-13,d*.115)-.35:-.35+Math.min(d*.078,3.8)+Math.max(0,d-48)*.018;const detail=(noise(x*.017,z*.017)-.5)*1.2+(noise(x*.042,z*.042)-.5)*.3;h+=detail*T.MathUtils.smoothstep(d,2,45);if(x< -250&&z> -480)h+=(noise(x*.005,z*.005)-.2)*Math.min(19,Math.max(0,(-x-250)*.065))*T.MathUtils.smoothstep(d,20,95);if(z<-570){const island=(cx:number,cz:number,r:number)=>Math.min(4.5,(r-Math.hypot(x-cx,z-cz))*.092);h=Math.max(h,island(-270,-785,73),island(285,-840,57));}return h}
export function biomeAt(x:number,z:number){return z< -535?'THE SALT COAST':x< -320?'RAINFOREST TRIBUTARY':z>385?'FLOODED GRASSLANDS':Math.hypot(x-125,z-225)<158?'STILLWATER LAGOON':'MANGROVE REACH'}
export function waterLevel(time:number){return Math.sin(time/130)*.16}
export function groundColor(h:number,x:number,z:number){const n=noise(x*.044,z*.044),region=biomeAt(x,z);const c=new T.Color(h<.4?(region==='THE SALT COAST'?0xe2d19e:0x9c885c):h<2?(region==='FLOODED GRASSLANDS'?0x6ba94d:0x5e954e):region==='RAINFOREST TRIBUTARY'?0x266a34:0x447d3c);return c.multiplyScalar(.88+n*.24)}
type Transform={position:T.Vector3;scale:T.Vector3;rotation:T.Quaternion;color?:T.Color};
const leafGeo=(()=>{const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute([0,0,-.45,.29,.03,-.16,.36,0,.12,.17,.045,.45,0,.03,.64,-.17,.045,.45,-.36,0,.12,-.29,.03,-.16,0,.12,.1],3));g.setAttribute('uv',new T.Float32BufferAttribute([.5,0,1,.25,1,.5,.75,.8,.5,1,.25,.8,0,.5,0,.25,.5,.5],2));g.setAttribute('color',new T.Float32BufferAttribute(Array(27).fill(1),3));g.setIndex([8,0,1,8,1,2,8,2,3,8,3,4,8,4,5,8,5,6,8,6,7,8,7,0]);g.computeVertexNormals();return g})();
const grassGeo=(()=>{const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute([-.06,0,0,.06,0,0,.1,.48,0,.02,.98,.1,-.045,.52,0],3));g.setAttribute('uv',new T.Float32BufferAttribute([0,0,1,0,1,.5,.5,1,0,.5],2));g.setIndex([0,1,2,0,2,4,4,2,3]);g.computeVertexNormals();return g})();
const branchGeo=new T.CylinderGeometry(.75,1,1,7),rockGeo=new T.IcosahedronGeometry(1,1),padGeo=lilyPadGeometry(),lotusGeo=lotusFlowerGeometry();
const crownGeo=(()=>{const g=new T.IcosahedronGeometry(1,1),p=g.attributes.position,colors=[];for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i),z=p.getZ(i),n=.83+noise(x*9+20,z*11+20)*.3;p.setXYZ(i,x*n,y*n,z*n);const c=new T.Color(0xffffff).multiplyScalar(.78+noise(x*13+40,z*17+40)*.28);colors.push(c.r,c.g,c.b)}g.setAttribute('color',new T.Float32BufferAttribute(colors,3));g.computeVertexNormals();return g})();
export class EstuaryWorld{
 group=new T.Group();waterMat:T.ShaderMaterial;water:T.Mesh;ground=new T.Group();chunks=new Map<string,{group:T.Group;ground:T.Mesh;floaters?:T.InstancedMesh;lotusMesh?:T.InstancedMesh;obstacles:{x:number;z:number;r:number}[]}>();obstacles:{x:number;z:number;r:number}[]=[];private center='';private detail=2;private terrain=terrainMaterial();private bark=barkMaterial();private leaves=new T.MeshStandardMaterial({color:0xffffff,side:T.DoubleSide,roughness:.92,vertexColors:true});private grasses=new T.MeshStandardMaterial({color:0xffffff,side:T.DoubleSide,roughness:.95});private stones=new T.MeshStandardMaterial({color:0x89917b,roughness:.95});private pads=new T.MeshStandardMaterial({color:0xffffff,vertexColors:true,side:T.DoubleSide,roughness:.76,polygonOffset:true,polygonOffsetFactor:-1,polygonOffsetUnits:-1});private lotuses=new T.MeshStandardMaterial({color:0xffffff,vertexColors:true,side:T.DoubleSide,roughness:.62,polygonOffset:true,polygonOffsetFactor:-2,polygonOffsetUnits:-2});private heightMap:T.DataTexture;private wind:{value:number}={value:0};
  constructor(private scene:T.Scene){scene.add(this.group);this.group.add(this.ground);this.heightMap=this.makeHeightMap();this.waterMat=new T.ShaderMaterial({transparent:true,depthWrite:false,side:T.DoubleSide,uniforms:{time:{value:0},sun:{value:new T.Vector3(-.5,.75,-.3)},cameraPos:{value:new T.Vector3()},heightMap:{value:this.heightMap},waterLevel:{value:0},worldSize:{value:WORLD_SIZE},warmth:{value:.7}},vertexShader:`varying vec3 vPos;void main(){vec4 p=modelMatrix*vec4(position,1.);vPos=p.xyz;gl_Position=projectionMatrix*viewMatrix*p;}`,fragmentShader:`precision highp float;varying vec3 vPos;uniform float time;uniform vec3 cameraPos;uniform vec3 sun;uniform sampler2D heightMap;uniform float waterLevel;uniform float worldSize;uniform float warmth;void main(){vec2 p=vPos.xz;float bottom=texture2D(heightMap,p/worldSize+.5).r*32.-16.;float depth=max(.0,waterLevel-bottom);float w1=sin(p.x*.36+p.y*.22+time*1.1);float w2=sin(p.y*.62-p.x*.12-time*.77);vec3 n=normalize(vec3(cos(p.x*.36+p.y*.22+time*1.1)*.055,1.,cos(p.y*.62-p.x*.12-time*.77)*.055));vec3 eye=normalize(cameraPos-vPos);float fresnel=pow(1.-max(dot(n,eye),0.),3.);float spec=pow(max(dot(reflect(-sun,n),eye),0.),100.);vec3 shallow=vec3(.26,.44,.32),deep=vec3(.07,.27,.28);vec3 col=mix(shallow,deep,smoothstep(.1,6.,depth));col=mix(col,vec3(.58,.75,.77),fresnel*.72);float c1=sin(p.x*.8+p.y*.7+time*1.4);float c2=sin(p.x*.6-p.y*.9-time*1.1);float caustic=pow(max(0.,sin(c1*2.5+c2*2.5)),4.)*(1.-smoothstep(.2,3.5,depth));col+=vec3(.85,.95,.82)*caustic*.18;float shoreFoam=(1.-smoothstep(.03,.42,depth))*(.5+.5*sin(p.x*4.+p.y*3.+time*2.2));col=mix(col,vec3(.92,.96,.94),shoreFoam*.42);float foam=(1.-smoothstep(.08,.55,depth))*smoothstep(.7,.98,sin(p.x*2.5+p.y*1.7+time*1.2)*.5+.5);vec3 specCol=mix(vec3(.72,.88,1.),vec3(1.,.86,.58),clamp(sun.y*2.,0.,1.));col+=foam*.25+(w1+w2)*.014+specCol*spec*.75;bool under=cameraPos.y<waterLevel;float mist=1.-exp(-length(cameraPos-vPos)*(under?.028:.0032));vec3 surfMist=mix(vec3(.16,.34,.45),vec3(.57,.73,.76),clamp(sun.y*2.5,0.,1.));col=mix(col,under?vec3(.12,.36,.31):surfMist,mist);float alpha=mix(.44,.83,smoothstep(0.,2.,depth));gl_FragColor=vec4(col,alpha);
#include <tonemapping_fragment>
#include <colorspace_fragment>
}`});this.water=new T.Mesh(new T.PlaneGeometry(5000,5000),this.waterMat);this.water.rotation.x=-Math.PI/2;this.water.renderOrder=3;this.group.add(this.water);this.setupWind(this.leaves,.14);this.setupWind(this.grasses,.1);this.makeLandmarks();}
 private makeHeightMap(){const size=256,data=new Uint8Array(size*size*4);for(let y=0;y<size;y++)for(let x=0;x<size;x++){const h=heightAt((x/(size-1)-.5)*WORLD_SIZE,(y/(size-1)-.5)*WORLD_SIZE),i=(y*size+x)*4;data[i]=Math.round(T.MathUtils.clamp((h+16)/32,0,1)*255);data[i+1]=data[i+2]=data[i];data[i+3]=255}const t=new T.DataTexture(data,size,size);t.magFilter=T.LinearFilter;t.needsUpdate=true;return t}
 private setupWind(material:T.MeshStandardMaterial,amount:number){material.onBeforeCompile=s=>{s.uniforms.uWind=this.wind;s.vertexShader='uniform float uWind;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>',`#include <begin_vertex>\ntransformed.x+=sin(uWind*1.2+position.y*2.2+position.x)*${amount.toFixed(3)}*max(position.y,0.);`)};}
 update(x:number,z:number,time:number,detail=2){this.wind.value=time;for(const child of this.group.children){const anchor=child.userData.anchor;if(anchor)child.visible=Math.hypot(anchor.x-x,anchor.z-z)<240}this.waterMat.uniforms.time.value=time;this.water.position.y=waterLevel(time);this.waterMat.uniforms.waterLevel.value=this.water.position.y;for(const c of this.chunks.values()){if(c.floaters)c.floaters.position.y=this.water.position.y+PAD_CLEARANCE;if(c.lotusMesh)c.lotusMesh.position.y=this.water.position.y+PAD_CLEARANCE;}const cx=Math.floor(x/CHUNK),cz=Math.floor(z/CHUNK),key=`${cx}:${cz}:${detail}`;if(key===this.center)return;if(detail!==this.detail){for(const c of this.chunks.values()){this.group.remove(c.group);c.ground.geometry.dispose();c.group.traverse(o=>{if(o instanceof T.InstancedMesh)o.dispose()})}this.chunks.clear()}this.center=key;this.detail=detail;const radius=detail>=3?3:2;const wanted=new Set<string>();for(let dx=-radius;dx<=radius;dx++)for(let dz=-radius;dz<=radius;dz++){const tx=cx+dx,tz=cz+dz;if(tx<-10||tx>=10||tz<-10||tz>=10)continue;const id=`${tx}:${tz}`;wanted.add(id);if(!this.chunks.has(id))this.createChunk(tx,tz,Math.max(Math.abs(dx),Math.abs(dz))<=1?1:0)}for(const[id,c]of this.chunks){if(!wanted.has(id)){this.group.remove(c.group);c.ground.geometry.dispose();c.group.traverse(o=>{if(o instanceof T.InstancedMesh)o.dispose()});this.chunks.delete(id)}}this.obstacles=[...this.chunks.values()].flatMap(c=>c.obstacles);}
 private inst(group:T.Group,geo:T.BufferGeometry,mat:T.Material,list:Transform[]){if(!list.length)return;const m=new T.InstancedMesh(geo,mat,list.length),o=new T.Object3D();list.forEach((p,i)=>{o.position.copy(p.position);o.quaternion.copy(p.rotation);o.scale.copy(p.scale);o.updateMatrix();m.setMatrixAt(i,o.matrix);if(p.color)m.setColorAt(i,p.color)});m.receiveShadow=true;m.castShadow=geo===branchGeo;m.computeBoundingSphere();group.add(m);return m}
 private createChunk(cx:number,cz:number,near:number){const rng=seeded((cx+20)*7193+(cz+20)*9923),group=new T.Group(),resolution=near?36:16,geo=new T.PlaneGeometry(CHUNK,CHUNK,resolution,resolution);geo.rotateX(-Math.PI/2);const p=geo.attributes.position,color=[];for(let i=0;i<p.count;i++){const x=p.getX(i)+cx*CHUNK+CHUNK/2,z=p.getZ(i)+cz*CHUNK+CHUNK/2,h=heightAt(x,z);p.setY(i,h);const c=groundColor(h,x,z);color.push(c.r,c.g,c.b)}geo.setAttribute('color',new T.Float32BufferAttribute(color,3));geo.computeVertexNormals();const ground=new T.Mesh(geo,this.terrain);ground.position.set(cx*CHUNK+CHUNK/2,0,cz*CHUNK+CHUNK/2);ground.receiveShadow=true;ground.userData.softwareIgnore=true;group.add(ground);
 const branches:Transform[]=[],leaves:Transform[]=[],crowns:Transform[]=[],grass:Transform[]=[],rocks:Transform[]=[],pads:Transform[]=[],lotuses:Transform[]=[],obstacles:{x:number;z:number;r:number}[]=[];const up=new T.Vector3(0,1,0);const add=(list:Transform[],x:number,y:number,z:number,sx:number,sy:number,sz:number,rx=0,ry=0,rz=0,c?:number)=>list.push({position:new T.Vector3(x,y,z),scale:new T.Vector3(sx,sy,sz),rotation:new T.Quaternion().setFromEuler(new T.Euler(rx,ry,rz)),color:c?new T.Color(c):undefined});
 const segment=(a:T.Vector3,b:T.Vector3,r:number)=>{const v=b.clone().sub(a);branches.push({position:a.clone().add(b).multiplyScalar(.5),scale:new T.Vector3(r,v.length(),r),rotation:new T.Quaternion().setFromUnitVectors(up,v.normalize())})};
 const centerRegion=biomeAt(cx*CHUNK+50,cz*CHUNK+50),treeCount=centerRegion==='RAINFOREST TRIBUTARY'?17:centerRegion==='FLOODED GRASSLANDS'?5:14;for(let i=0;i<treeCount;i++){const x=cx*CHUNK+rng()*CHUNK,z=cz*CHUNK+rng()*CHUNK,h=heightAt(x,z);if(h<.08||h>30||z<-620||LANDMARKS.some(l=>Math.hypot(l.x-x,l.z-z)<10))continue;const river=Math.abs(channelDistance(x,z)),rain=biomeAt(x,z)==='RAINFOREST TRIBUTARY';const tall=rain?10+rng()*10:4+rng()*7,r=.28+rng()*.3,base=new T.Vector3(x,h,z),mid=new T.Vector3(x+(rng()-.5)*.5,h+tall*.53,z+(rng()-.5)*.5),top=new T.Vector3(x+(rng()-.5)*1.6,h+tall,z+(rng()-.5)*1.6);segment(base,mid,r);segment(mid,top,r*.68);obstacles.push({x,z,r:r+.3});
 for(let j=0;j<(near?6:4);j++){const a=j*1.047+rng()*.6,spread=(rain?4:2)+rng()*2.5,tip=top.clone().add(new T.Vector3(Math.cos(a)*spread,-rng()*1.5,Math.sin(a)*spread));segment(mid.clone().lerp(top,.45),tip,r*.23);add(crowns,tip.x,tip.y-.12,tip.z,2.1+rng()*.7,.9+rng()*.5,2.2+rng()*.8,.05,rng()*6.28,(rng()-.5)*.22,rng()>.5?0x4e753b:0x416637);for(let k=0;k<(near?13:7);k++){const angle=rng()*6.28,dist=rng()*2;add(leaves,tip.x+Math.cos(angle)*dist,tip.y+(rng()-.5)*1.4,tip.z+Math.sin(angle)*dist,.9+rng()*.7,.7,1.4+rng()*.8,(rng()-.5)*1.35,rng()*6.28,(rng()-.5)*1.05,rng()>.5?0x4e7c3d:0x3f6e38)}}
 if(river<48){for(let j=0;j<5;j++){const a=j*1.25,tip=base.clone().add(new T.Vector3(Math.cos(a)*(1.7+rng()),0,Math.sin(a)*(1.7+rng())));tip.y=heightAt(tip.x,tip.z)+.12;const bend=base.clone().add(new T.Vector3(Math.cos(a)*.65,1.2,Math.sin(a)*.65));segment(base.clone().add(new T.Vector3(0,2,0)),bend,r*.3);segment(bend,tip,r*.24)}}}
 for(let i=0;i<(near?190:65);i++){const x=cx*CHUNK+rng()*CHUNK,z=cz*CHUNK+rng()*CHUNK,h=heightAt(x,z);if(h<-.15||h>28||LANDMARKS.some(l=>Math.hypot(l.x-x,l.z-z)<6))continue;const wet=h<1.5,scale=wet?1.1+rng()*1.6:.45+rng()*.9;for(let j=0;j<(near?5:3);j++)add(grass,x+(rng()-.5)*.5,h,z+(rng()-.5)*.5,.8,scale,.8,0,rng()*6.28,(rng()-.5)*.35,wet?0x84aa54:rng()>.5?0x7ea44e:0x51843e);if(i%11===0&&h>.3){add(crowns,x,h+.65,z,1.3,.8,1.5,0,rng()*6.28,0,0x4f7c35)}if(i%14===0&&h>.1&&h<3.5){const bloomCol=rng()<0.35?0xee3224:rng()<0.7?0xec407a:0xffb300;add(crowns,x,h+.45,z,.72,.55,.72,0,rng()*6.28,0,bloomCol);}if(i%6===0&&h>.15){const size=.35+rng()*1.9;add(rocks,x,h+size*.2,z,size,size*.42,size*.78,rng(),rng()*6.28,rng())}if(i%13===0&&h<1.8){const a=new T.Vector3(x,h+.25,z),b=new T.Vector3(x+3+rng()*4,h+.5,z+1);segment(a,b,.18+rng()*.2)}}
 for(let i=0;i<30;i++){const x=cx*CHUNK+rng()*CHUNK,z=cz*CHUNK+rng()*CHUNK,h=heightAt(x,z);if(h<-.45&&h>-3.6&&z> -100){const s=.4+rng()*.5;add(pads,x,0,z,s,1,s,0,rng()*6.28,0);if(rng()<0.42){const flowerColor=rng()<0.33?0xffffff:rng()<0.66?0xfc8fae:0xffe082;add(lotuses,x,.01,z,s*.62,s*.62,s*.62,0,rng()*6.28,0,flowerColor);}}}
 this.inst(group,branchGeo,this.bark,branches);this.inst(group,crownGeo,this.leaves,crowns);this.inst(group,leafGeo,this.leaves,leaves);this.inst(group,grassGeo,this.grasses,grass);this.inst(group,rockGeo,this.stones,rocks);const floaters=this.inst(group,padGeo,this.pads,pads);if(floaters){floaters.name='Floating lily pads';floaters.position.y=this.water.position.y+PAD_CLEARANCE;floaters.renderOrder=4;}const lotusMesh=this.inst(group,lotusGeo,this.lotuses,lotuses);if(lotusMesh){lotusMesh.name='Blooming lotus flowers';lotusMesh.position.y=this.water.position.y+PAD_CLEARANCE;lotusMesh.renderOrder=5;}this.group.add(group);this.chunks.set(`${cx}:${cz}`,{group,ground,floaters,lotusMesh,obstacles});}
 private makeLandmarks(){const wood=new T.MeshStandardMaterial({color:0x76654e,roughness:1}),stone=new T.MeshStandardMaterial({color:0xa0987e,roughness:1}),box=new T.BoxGeometry(1,1,1);const put=(group:T.Group,mat:T.Material,x:number,y:number,z:number,sx:number,sy:number,sz:number)=>{const m=new T.Mesh(box,mat);m.position.set(x,y,z);m.scale.set(sx,sy,sz);m.castShadow=true;m.receiveShadow=true;group.add(m);return m};
 const jetty=new T.Group(),l=LANDMARKS[0];jetty.position.set(l.x,heightAt(l.x,l.z),l.z);for(let i=0;i<19;i++)put(jetty,wood,-i*.48,.55,0,.45,.13,2.9);for(let i=0;i<4;i++)for(const s of [-1,1])put(jetty,wood,-i*2.6,-.1,s*1.3,.23,1.8,.23);put(jetty,wood,-4.5,.34,-1,9,.2,.2);put(jetty,wood,-4.5,.34,1,9,.2,.2);jetty.userData.anchor={x:l.x,z:l.z};this.group.add(jetty);
 const wreck=new T.Group(),w=LANDMARKS[3];wreck.position.set(w.x,heightAt(w.x,w.z)+.15,w.z);wreck.rotation.y=.45;wreck.rotation.z=.12;for(let i=0;i<16;i++){const z=(i-7.5)*.5,width=1.6*Math.sqrt(Math.max(0,1-(z/4.2)**2));put(wreck,wood,0,.06,z,width*2,.12,.47);for(const s of [-1,1])put(wreck,wood,s*width,.5,z,.11,.85,.5)}put(wreck,wood,0,.15,0,.14,.18,8.4);wreck.userData.anchor={x:w.x,z:w.z};this.group.add(wreck);
 const ruins=new T.Group();for(let i=0;i<9;i++){const a=i*.7;const x=170+Math.cos(a)*4,z=490+Math.sin(a)*4;const m=put(ruins,stone,x,heightAt(x,z)+.65,z,1.3,1.3+rngFor(i),.8);m.rotation.y=a;m.rotation.z=(i%3-1)*.1}ruins.userData.anchor={x:170,z:490};this.group.add(ruins);
 const fig=new T.Group(),f=LANDMARKS[4];fig.position.set(f.x,heightAt(f.x,f.z),f.z);for(let i=0;i<7;i++){const a=i*.9;const trunk=new T.Mesh(new T.CylinderGeometry(.5,1.1,13,9),this.bark);trunk.position.set(Math.cos(a),6.5,Math.sin(a));trunk.rotation.z=Math.cos(a)*.04;fig.add(trunk)}for(let i=0;i<9;i++){const crown=new T.Mesh(crownGeo,new T.MeshStandardMaterial({color:0x4b6e36,roughness:.94,vertexColors:true}));crown.position.set(Math.cos(i*.7)*4,13+Math.sin(i)*1.5,Math.sin(i*.7)*4);crown.scale.set(5,2.3,5);fig.add(crown)}fig.userData.anchor={x:f.x,z:f.z};this.group.add(fig);
 }
 dispose(){for(const c of this.chunks.values()){c.ground.geometry.dispose();c.group.traverse(o=>{if(o instanceof T.InstancedMesh)o.dispose()})}this.heightMap.dispose();[this.terrain,this.bark,this.leaves,this.grasses,this.stones,this.pads,this.lotuses,this.waterMat].forEach(m=>m.dispose());this.scene.remove(this.group)}
}
function rngFor(i:number){return noise(i*4.31,i)*.7}
export function makeWorld(scene:T.Scene){return new EstuaryWorld(scene)}
